version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: churnsense-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sudhanshu_2026
      POSTGRES_DB: churnsense
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churnsense-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:Sudhanshu_2026@db:5432/churnsense
      - JWT_SECRET=SudhanshuSecretKey2026_EnterpriseGradeSecret
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:18-alpine
    container_name: churnsense-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-next:/app
    command: sh -c "npm install && npm run build && npm run start"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  pgdata:
